### ISSUE TITLE
cfn stack name should have some entropy

### ISSUE THREAD

**Issue by smiller171** [rhythmictech/terraform-aws-imagebuilder-component-ansible#4]
https://github.com/rhythmictech/terraform-aws-imagebuilder-component-ansible/blob/55ab74b820f62d09536250e16f1579b2267c82f4/main.tf#L12-L12

**Comment by cdaniluk** [comment]
@smiller171 wasn't this fixed in #7?

**Comment by smiller171** [comment]
@cdaniluk yep!
